#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE ${ODK_USER} WITH LOGIN PASSWORD '${ODK_PASSWORD}';
    CREATE DATABASE ${ODK_DB} OWNER ${ODK_USER};
    GRANT CONNECT ON DATABASE ${ODK_DB} TO ${ODK_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$ODK_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS CITEXT;
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE EXTENSION IF NOT EXISTS pgrowlocks;

    GRANT ALL PRIVILEGES ON SCHEMA public TO ${ODK_USER};
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${ODK_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${ODK_USER};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${ODK_USER};
EOSQL