#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE ${OPENPROJECT_USER} WITH LOGIN PASSWORD '${OPENPROJECT_PASSWORD}';
    CREATE DATABASE ${OPENPROJECT_DB} OWNER ${OPENPROJECT_USER};
    GRANT CONNECT ON DATABASE ${OPENPROJECT_DB} TO ${OPENPROJECT_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$OPENPROJECT_DB" <<-EOSQL
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${OPENPROJECT_USER};
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${OPENPROJECT_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${OPENPROJECT_USER};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${OPENPROJECT_USER};
EOSQL